### ISSUE TITLE
Flask-vue-curd on Google Cloud

### ISSUE THREAD

**Issue by siliconberry** [testdrivenio/flask-vue-crud#12]
Hi, 

Can you please tell me how I can load this on Google Cloud ? Since it needs 2 ports to be used(5000 and 8080), How can I deploy and access it on Google Cloud ?

**Comment by J-rayX** [comment]
@siliconberry Check to see if this answers your question: 

https://medium.com/@jeremy.from.earth/configuring-a-full-stack-development-environment-with-app-engine-flask-vue-d3a45743c08c
