### ISSUE TITLE
Changes are not persistent

### ISSUE THREAD

**Issue by msoutopico** [testdrivenio/flask-vue-crud#13]
Thanks for the tutorial, Michael. Very illustrative. 

However, the added or the updated books are not kept when you restart the application. Changes are not persistent. If this is normal because the part to save changes to the backend is not included, I'd be grateful for some tips about which path one should go to add that. 

THanks. 
Cheers, Manuel

**Comment by joegiglio** [comment]
Yes, @msoutopico.  The backend code does not persist the changes to any database.  See this function to see that it only appends the array which is in memory: https://github.com/testdrivenio/flask-vue-crud/blob/217c807a7fcb667546b3be4b17a85e9ac5eee4ac/server/app.py#L70

I recently uploaded a Flask-CRUD repo that has some basic database operations that may be useful to you.  Please see:   [https://github.com/joegiglio/flask-crud](url)
