### ISSUE TITLE
How to deploy this?

### ISSUE THREAD

**Issue by baristaGeek** [testdrivenio/flask-vue-crud#4]
Does the project need to be restructured in order be deployed?

Would love to see a tutorial on how to deploy this?

**Comment by mjhea0** [comment]
@baristaGeek no. I would deploy them separately, much like how it's done in the [Microservices with Docker, Flask, and React](https://testdriven.io/courses/microservices-with-docker-flask-and-react/) course with Docker. Where are you looking to deploy it to? Heroku? DigitalOcean? AWS EC2?

**Comment by mjhea0** [comment]
One example: https://testdriven.io/blog/deploying-flask-to-heroku-with-docker-and-gitlab/
